### ISSUE TITLE
hash-ref: contract violation on event-guild-member-update

### ISSUE THREAD

**Issue by vascocosta** [nitros12/racket-cord#1]
First of all, thanks for this very comprehensive Discord lib thanks to which I can improve my knowledge of Racket implementing a useful Discord bot. I should also say that it works flawlessly and I'm only posting this because I saw the contract violation warning messages and thought you might be interested. So here it is with user info removed from the output (it happens during event-guild-member-update):

hash-ref: contract violation
  expected: hash?
  given: (list (member (user "...      
  argument position: 1st
  other arguments...:
   "908329..."
  context...:
   /home/gluon/.racket/7.1/pkgs/racket-cord/events.rkt:174:0: event-guild-member-update                                                
   /home/gluon/.racket/7.1/pkgs/racket-cord/utils.rkt:25:2: for-loop
   /home/gluon/.racket/7.1/pkgs/racket-cord/utils.rkt:24:0: each

**Comment by nitros12** [comment]
Thanks, 54dcbf3d3b07b4630fb70b1ac43660cfbcc0b582 should have fixed this issue
